apiVersion: v1
kind: Pod
metadata:
  name: vault-validator
  namespace: vault
  labels:
    app: vault-validator
    vault-sidecar-injector: enabled
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/service: ""
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/role: ""
    vault.hashicorp.com/agent-inject-secret-env: ""
    vault.hashicorp.com/agent-inject-template-env: |
      {{- with secret "" -}}
        {{ range $k, $v := .Data.data }}
          export {{ $k }}="{{ $v }}"
        {{ end }}
      {{- end }}
spec:
  containers:
  - name: vault-validator
    image: python:3.9-slim-buster
    command: ["/bin/sh", "-ec"]
    args:
      - |
        . /vault/secrets/env
        while true; do sleep 10 ;done